# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube Server service connection'
    scannerMode: 'cli'
    configMode: 'manual'
    cliSources: '.'
    clioptions: 
